## Семинар 1 Индекс

## Intro

### работа с файлами и папками

In [1]:
import os

curr_dir = os.getcwd()
filepath = os.path.join(curr_dir, 'test.txt')

### os.path  
путь до файла

In [2]:
# возвращает полный путь до папки/файла по имени файла / папки
print(os.path.abspath(filepath))


# возвращает имя файла / папки по полному ти до него
print(os.path.basename(filepath))


# проверить существование директории - True / False
print(os.path.exists(curr_dir))

/content/test.txt
test.txt
True


### os.listdir  
возвращает список файлов в данной директории

In [3]:
os.listdir(curr_dir)

['.config', 'friends-data.zip', 'sample_data']

При обходе файлов не забывайте исключать системные директории, такие как .DS_Store

### os.walk
root - начальная директория  
dirs - список поддиректорий (папок)   
files - список файлов в этих поддиректориях  

In [4]:
for root, dirs, files in os.walk(curr_dir):
    for name in files:
        print(os.path.join(root, name))

/content/friends-data.zip
/content/.config/active_config
/content/.config/config_sentinel
/content/.config/gce
/content/.config/.last_update_check.json
/content/.config/.last_opt_in_prompt.yaml
/content/.config/.last_survey_prompt.yaml
/content/.config/.metricsUUID
/content/.config/configurations/config_default
/content/.config/logs/2020.09.14/16.31.01.862680.log
/content/.config/logs/2020.09.14/16.30.40.318937.log
/content/.config/logs/2020.09.14/16.30.45.960190.log
/content/.config/logs/2020.09.14/16.30.25.423853.log
/content/.config/logs/2020.09.14/16.31.02.575348.log
/content/.config/logs/2020.09.14/16.30.06.614788.log
/content/sample_data/README.md
/content/sample_data/anscombe.json
/content/sample_data/mnist_test.csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_train.csv
/content/sample_data/california_housing_test.csv


> __os.walk__ возвращает генератор, это значит, что получить его элементы можно только проитерировавшись по нему  
но его легко можно превратить в list и увидеть все его значения

In [5]:
list(os.walk(curr_dir))

[('/content', ['.config', 'sample_data'], ['friends-data.zip']),
 ('/content/.config',
  ['configurations', 'logs'],
  ['active_config',
   'config_sentinel',
   'gce',
   '.last_update_check.json',
   '.last_opt_in_prompt.yaml',
   '.last_survey_prompt.yaml',
   '.metricsUUID']),
 ('/content/.config/configurations', [], ['config_default']),
 ('/content/.config/logs', ['2020.09.14'], []),
 ('/content/.config/logs/2020.09.14',
  [],
  ['16.31.01.862680.log',
   '16.30.40.318937.log',
   '16.30.45.960190.log',
   '16.30.25.423853.log',
   '16.31.02.575348.log',
   '16.30.06.614788.log']),
 ('/content/sample_data',
  [],
  ['README.md',
   'anscombe.json',
   'mnist_test.csv',
   'mnist_train_small.csv',
   'california_housing_train.csv',
   'california_housing_test.csv'])]

### чтение файла 

In [6]:
#filepath = 'test.txt'


# одним массивом  
#with open(fpath, 'r') as f:  
#    text = f.read() 

    
#по строкам, в конце каждой строки \n  
#with open(fpath, 'r') as f:   
#    text = f.readlines() 

    
#по строкам, без \n   
#with open(fpath, 'r') as f:   
#    text = f.read().splitlines() 

Напоминание про enumerate:    
> При итерации по списку вы можете помимо самого элемента получить его порядковый номер    
``` for i, element in enumerate(your_list): ...  ```    
Иногда для получения элемента делают так -  ``` your_list[i] ```, не надо так

### CountVectorizer

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
 
# инициализируем
vectorizer = CountVectorizer()

# составляем корпус документов
corpus = [
  'слово1 слово2 слово3',
  'слово2 слово3',
  'слово1 слово2 слово1',
  'слово4'
]

# считаем
X = vectorizer.fit_transform(corpus)
 
# получится следующая структура:
#        | слово1 | слово2 | слово3 | слово4
# текст1 |   1    |    1   |   1    |   0
# текст2 |   0    |    1   |   1    |   0
# текст3 |   2    |    1   |   0    |   0
# текст4 |   0    |    0   |   0    |   1
 
# чтобы получить сгенерированный словарь, из приведенной структуры CountVectorizer
# порядок совпадает с матрицей
vectorizer.get_feature_names()  # ['слово1', 'слово2', 'слово3', 'слово4']
 
# чтобы узнать индекс токена в словаре
print(vectorizer.vocabulary_.get('слово3')) # вернет 2
 
# показать матрицу
print(X.toarray())
 
# теперь можно быстро подсчитать вектор для нового документа
vectorizer.transform(["слово1 слово4 слово4"])  # результат [[1 0 0 2]]
 
# чтобы узнать количественное вхождение каждого слова:
matrix_freq = np.asarray(X.sum(axis=0)).ravel()
final_matrix = np.array([np.array(vectorizer.get_feature_names()), matrix_freq])

2
[[1 1 1 0]
 [0 1 1 0]
 [2 1 0 0]
 [0 0 0 1]]


##  Индекс 

Сам по себе индекс - это просто формат хранения данных, он не может осуществлять поиск. Для этого необходимо добавить к нему определенную метрику. Это может быть что-то простое типа булева поиска, а может быть что-то более специфическое или кастомное под задачу.

Давайте посмотрим, что полезного можно вытащить из самого индекса.    
По сути, индекс - это информация о частоте встречаемости слова в каждом документе.   
Из этого можно понять, например:
1. какое слово является самым часто употребимым / редким
2. какие слова встречаются всегда вместе - так можно парсить твиттер, fb, форумы и отлавливать новые устойчивые выражения в речи
3. как эти документы кластеризуются по N тематикам согласно словам, которые в них упоминаются 

## __Задача__: 

**Data:** Коллекция субтитров сезонов Друзей. Одна серия - один документ.

**To do:** 

**1 Создайте индекс этой базы в формате json и в формате матрицы Term-Document**

Компоненты вашей реализации:
    - функция препроцессинга данных
    - функция индексирования данных

**2 С помощью обратного индекса в формате Term-Document посчитайте:** 


a) какое слово является самым частотным

b) какое самым редким

c) какой набор слов есть во всех документах коллекции

d) кто из главных героев статистически самый популярный? 



[download_friends_corpus](https://yadi.sk/d/4wmU7R8JL-k_RA?w=1)

Напоминание про defaultdict: 
> Если ваш код предполагает использование multiple values словаря, рекомендую использовать ``` collections.defaultdict ```                          
> Так можно избежать конструкции ``` dict.setdefault(key, default=None) ```

> ```from collections import defaultdict
d = defaultdict(list)
d['example'].append('example1')
d['example'].append('example2')```

In [8]:
### _check : в коллекции должно быть около 165 файлов
import re
from zipfile import ZipFile
with ZipFile('friends-data.zip', 'r') as zip:
  zip.printdir()
  zip.extractall()
#curr_dir = os.getcwd()
#filepath = os.path.join(curr_dir, 'friends-data.zip')
#print(os.path.exists(curr_dir))
#for root, dirs, files in os.walk(curr_dir):
#    for name in files:
#        print(os.path.join(root, name))

File Name                                             Modified             Size
friends-data/Friends - season 1/Friends - 1x01 - The One Where Monica Gets A Roommate.ru.txt 2020-09-09 17:22:52        30277
friends-data/Friends - season 1/Friends - 1x02 - The One With The Sonogram At The End.ru.txt 2020-09-09 17:22:52        18156
friends-data/Friends - season 1/Friends - 1x03 - The One With The Thumb.ru.txt 2020-09-09 17:22:52        20203
friends-data/Friends - season 1/Friends - 1x04 - The One With George Stephanopoulos.ru.txt 2020-09-09 17:22:52        23082
friends-data/Friends - season 1/Friends - 1x05 - The One With The East German Laundry Detergent.ru.txt 2020-09-09 17:22:52        21237
friends-data/Friends - season 1/Friends - 1x06 - The One With The Butt.ru.txt 2020-09-09 17:22:52        21494
friends-data/Friends - season 1/Friends - 1x07 - The One With The Blackout.ru.txt 2020-09-09 17:22:52        17662
friends-data/Friends - season 1/Friends - 1x08 - The One Where Nana Di

In [9]:
curr_dir = os.getcwd()
dir_lis = list(os.walk(curr_dir))

In [10]:
dir_lis

[('/content',
  ['.config', 'friends-data', 'sample_data'],
  ['friends-data.zip']),
 ('/content/.config',
  ['configurations', 'logs'],
  ['active_config',
   'config_sentinel',
   'gce',
   '.last_update_check.json',
   '.last_opt_in_prompt.yaml',
   '.last_survey_prompt.yaml',
   '.metricsUUID']),
 ('/content/.config/configurations', [], ['config_default']),
 ('/content/.config/logs', ['2020.09.14'], []),
 ('/content/.config/logs/2020.09.14',
  [],
  ['16.31.01.862680.log',
   '16.30.40.318937.log',
   '16.30.45.960190.log',
   '16.30.25.423853.log',
   '16.31.02.575348.log',
   '16.30.06.614788.log']),
 ('/content/friends-data',
  ['Friends - season 3',
   'Friends - season 7',
   'Friends - season 5',
   'Friends - season 2',
   'Friends - season 4',
   'Friends - season 1',
   'Friends - season 6'],
  []),
 ('/content/friends-data/Friends - season 3',
  [],
  ['Friends - 3x12 - The One With All The Jealousy.ru.txt',
   "Friends - 3x14 - The One With Phoebe's Ex-Partner.ru.txt",
 

In [11]:
words = []
episode_dict = {}
for root, dirs, files in os.walk(curr_dir):
    for name in files:
        joined_path = str(os.path.join(root, name))
        if joined_path.endswith('.txt'):
          #print("Yes!")v
          corpus = []
          vectorizer = CountVectorizer()
          with open(joined_path, 'r', encoding='utf-8-sig') as f:
            #names.append(name)   
            text = f.read()
            #print(text)
            #print(text)
            text = re.sub('[!,-.\'"?#$%^&*;:1234567890@_]',' ',text)
            text = re.sub('\n',' ', text)
            text = text.lower()
            corpus.append(text)
            for t in text.split():
              words.append(t)
            episode_dict[name] = text
          X = vectorizer.fit_transform(corpus)
          print(X.toarray())
          
# import numpy as np
 
# инициализируем

# составляем корпус документов
#corpus = [
#  'слово1 слово2 слово3',
#  'слово2 слово3',
#  'слово1 слово2 слово1',
#  'слово4'
#]

# считаем
#X = vectorizer.fit_transform(corpus)
 
# получится следующая структура:
#        | слово1 | слово2 | слово3 | слово4
# текст1 |   1    |    1   |   1    |   0
# текст2 |   0    |    1   |   1    |   0
# текст3 |   2    |    1   |   0    |   0
# текст4 |   0    |    0   |   0    |   1
 
# чтобы получить сгенерированный словарь, из приведенной структуры CountVectorizer
# порядок совпадает с матрицей
#vectorizer.get_feature_names()  # ['слово1', 'слово2', 'слово3', 'слово4']
 
# чтобы узнать индекс токена в словаре
#print(vectorizer.vocabulary_.get('слово3')) # вернет 2
 
# показать матрицу
#print(X.toarray())
 
# теперь можно быстро подсчитать вектор для нового документа
#vectorizer.transform(["слово1 слово4 слово4"])  # результат [[1 0 0 2]]
 
# чтобы узнать количественное вхождение каждого слова:
matrix_freq = np.asarray(X.sum(axis=0)).ravel()
final_matrix = np.array([np.array(vectorizer.get_feature_names()), matrix_freq])

Выходные данные были обрезаны до нескольких последних строк (5000).
  40  1  1  2  1  2  1]]
[[ 1  1  1  1  1  1  1  1  1  1  2  1  1  1  5  2  1  1  1  1  2  1  1  2
   1 10  1  3  3  1  1  1  1  1  1  1  3  1  2  4  2  9  1  1  5  7  1  8
   2  1  4  1  5  3  1  4  1  2  1  1  1  1  1  2  1  1  1  1  1  1  1  2
   2  2  1  3  1  1  1  1  1  1  2  1  3  2  1  1  1  1  1  8  1  1  4  1
   1  1  1  1  1  1  1  6  1  1 10  1  1  1  2  1  1  1  1  1  1  1  1  1
   1  1  1  3  1  1  1  2  1  1  3  2  1  1  3  1  1  1  1  1  1 17  5  3
   2  1  1  1  1  1  1  1  2  2  1  4  3  2  2  1  2  1  1  1  2  3  1 15
   1  1  1  1  1  3  1  1  2  1  1  7  1  3  1  1  2  1  1  4  1  1  1  2
   1  2  1  1  4  1  1 12  1  3  9 14  4  9 11  1  1  1  1 14  1  1  1  1
   1  1  1  1  1  8  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1
   1  4  4  1  1  1  1  2  2  2  1  3  2  2  3  9  1  1  2  2  8  1  1  1
   2  1  6  2  2  1  1  1  1  1  1  1  3  1  1  1  2  1 19  1  1  1  3  2
   1  3  1  1  1  1

In [43]:
import pickle
with open('matrix.pkl', 'wb') as pick:
  pickle.dump(X.toarray(), pick)

In [14]:
import re

In [31]:
import collections
c = collections.Counter()

for word in words:
  c[word] += 1

print(c)
print(c.most_common(1)) # Самый часто встречающийся элемент
n = 2
print(c.most_common()[:-n-1:-1]) # Наиболее редко встречающийся элемент

Counter({'я': 13008, 'не': 9456, 'что': 8937, 'ты': 7330, 'это': 6370, 'и': 5891, 'в': 4918, 'с': 3496, 'а': 3485, 'на': 3245, 'так': 3102, 'да': 2995, 'нет': 2911, 'мне': 2834, 'как': 2808, 'у': 2807, 'мы': 2433, 'меня': 2400, 'то': 2159, 'он': 2121, 'но': 2020, 'о': 1962, 'она': 1827, 'тебя': 1774, 'тебе': 1738, 'ну': 1690, 'бы': 1606, 'вы': 1531, 'же': 1510, 'если': 1324, 'вот': 1296, 'все': 1254, 'всё': 1248, 'за': 1237, 'просто': 1237, 'хорошо': 1115, 'ладно': 1114, 'его': 1093, 'когда': 1033, 'знаю': 1023, 'было': 972, 'из': 962, 'мой': 953, 'только': 951, 'привет': 908, 'может': 898, 'могу': 871, 'очень': 863, 'есть': 854, 'знаешь': 833, 'они': 831, 'уже': 821, 'чтобы': 793, 'будет': 790, 'спасибо': 783, 'боже': 778, 'по': 764, 'росс': 746, 'там': 743, 'к': 699, 'кто': 699, 'для': 684, 'джоуи': 682, 'был': 674, 'ещё': 671, 'нас': 649, 'почему': 643, 'сейчас': 640, 'хочу': 633, 'её': 621, 'ничего': 620, 'тут': 620, 'быть': 614, 'здесь': 605, 'надо': 589, 'фиби': 575, 'правда': 57

In [ ]:
import json

json_dict = {}
word_list = []
for w in words:
  word_dict = {}
  for episode_k, episode_v in episode_dict.items():
    num = 0
    for splitter in episode_v.split():
      word_list.append(splitter)
      if w == splitter:
        num += 1
    word_dict[episode_k] = num
  json_dict[w] = word_dict
  #print(json_dict[w])

with open("episodes.json","w",encoding="utf-8"):
  json.dumps(json_dict)

# Работает очень долго, я не знаю, как ускорить процесс.

In [41]:
chand = 0
mon = 0
rach = 0
phoeb = 0
ros = 0
joe = 1 # "Джои" тоже учитывается
for word in episode_dict.values():
  chandler = re.findall("чендлер", word)
  monica = re.findall("моник", word)
  rachel = re.findall("рэйчел", word)
  phoebe = re.findall("фиби", word)
  ross = re.findall("росс", word)
  for r in ross:
    if len(r) > 4:
      ross.pop(r)
  joey = re.findall("джоуи", word)
  chand += len(chandler)
  mon += len(monica)
  rach += len(rachel)
  phoeb += len(phoebe)
  ros += len(ross)
  joe += len(joey)

print(chand) # Чендлер
print(mon) # Моника
print(rach) # Рэйчел
print(phoeb) # Фиби
print(ros) # Росс
print(joe) # Джоуи

727
688
237
576
1052
683


In [ ]:
main_list = []
for w in words:
  record = 0
  for val in episode_dict.values():
    if re.findall(w, val):
      record += 1
    if record == len(episode_dict.values()):
      main_list.append(w)